### ISSUE TITLE
Grouping and listing package names

### ISSUE THREAD

**Issue by jerinjohnk** [arochedy/react-native-check-new-archi#2]
It would be great if there's an additional option of 
1)—-group - Groups all supported, notSupported, and notFound packages together and prints them instead of printing each separately. 
Until it's being executed, a loader, for example, scanning 2 of 27 packages, etc., can be shown.
2) Printing only user selected groups like --s=supported, --ns=notSupported, --nf=notFound etc.
3) Skipping a particular package group would be pretty helpful.

**Comment by arochedy** [comment]
ok I started working on this.

**Comment by jerinjohnk** [comment]
Oh great. 
I wanted your approval before adding these features.
Hence, I added them as ideas. 
Glad to know you liked it.

**Comment by arochedy** [comment]
done in this PR : https://github.com/arochedy/react-native-check-new-archi/pull/4

**Comment by jerinjohnk** [comment]
I added a few code enhancements in PR [`#8`](https://github.com/arochedy/react-native-check-new-archi/pull/8). As there are some drastic changes, please test it thoroughly before publishing.
